### ISSUE TITLE
Minecraft 1.21.11 Support

### ISSUE THREAD

**Issue by hamcoremusic** [pop4959/ChunkyBorder#113]
Hi there!

Are there any plans on expanding the version support to 1.21.11? I did see #104 about it being 1.21.5+ soon.

**Comment by pop4959** [comment]
Yes full support is still planned for 1.21.11 and all versions leading up to it, hopefully sometime over the next few months. I know it has been a long time coming. The PR has not seen much progress and unfortunately I have been very busy personally, which is why there hasn't been time for it yet.

In the meanwhile if there is anything aside from the rendering code that needs updating please feel free to let me know by making a new issue. Although so far I haven't seen any other reports of it not working so you may have luck using the old versions still.

**Comment by hamcoremusic** [comment]
No worries! Take your time. Previous versions of the mod will certainly not work on 1.21.11 correct?

**Comment by pop4959** [comment]
> No worries! Take your time. Previous versions of the mod will certainly not work on 1.21.11 correct?

I just checked to be sure and the latest Chunky Border version seems to work on Fabric 1.21.11.

**Comment by NiceKaleido** [comment]
Can confirm it working up to 1.21.11 - but with 26.1.2 it breaks.

```
[09:27:45] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'ChunkyBorder' (chunkyborder) 1.2.24 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:202)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:66)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
```

**Comment by Liquiqe** [comment]
@pop4959  Please update to version 1.21.11 Neoforge

**Comment by pop4959** [comment]
> [@pop4959](https://github.com/pop4959) Please update to version 1.21.11 Neoforge

Is the current version not working on 1.21.11, have you tried it?

**Comment by Liquiqe** [comment]
> > [@pop4959](https://github.com/pop4959) Please update to version 1.21.11 Neoforge
> 
> Is the current version not working on 1.21.11, have you tried it?

Yes, it doesn’t work on version 1.21.11 (21.11.42 neoforge); I’ve attached the crash report

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2026-06-10 21:16:16
Description: Mod loading failures have occurred; consult the issue messages for more details

net.neoforged.neoforge.logging.CrashReportExtender$ModLoadingCrashException: Mod loading has failed


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at net.neoforged.fml.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:254) ~[loader-10.0.36.jar:10.0] {}
-- Mod loading issue for: chunkyborder --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/resources/ResourceLocation
                at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
                at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?] {}
                at java.base/java.lang.Class.getDeclaredMethods(Unknown Source) ~[?:?] {}
                at net.neoforged.bus.EventBus.register(EventBus.java:105) ~[bus-8.0.5.jar:?] {}
                at TRANSFORMER/chunkyborder@1.2.24/org.popcraft.chunkyborder.ChunkyBorderNeoForge.<init>(ChunkyBorderNeoForge.java:64) ~[ChunkyBorder-NeoForge-1.2.24.jar:?] {}
                at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?] {}
                at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
                at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
                at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:118) ~[loader-10.0.36.jar:10.0] {}
                at net.neoforged.fml.ModLoader.lambda$constructMods$0(ModLoader.java:125) ~[loader-10.0.36.jar:10.0] {}
                at net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$4(ModLoader.java:203) ~[loader-10.0.36.jar:10.0] {}
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

        Mod file: /data/mods/ChunkyBorder-NeoForge-1.2.24.jar
        Failure message: ChunkyBorder (chunkyborder) has failed to load correctly
                java.lang.NoClassDefFoundError: net/minecraft/resources/ResourceLocation
        Mod version: 1.2.24
        Mod issues URL: https://github.com/pop4959/ChunkyBorder/issues
        Exception message: java.lang.ClassNotFoundException: net.minecraft.resources.ResourceLocation
Stacktrace:
        at net.neoforged.fml.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:254) ~[loader-10.0.36.jar:10.0] {}
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
        at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?] {}
        at java.base/java.lang.Class.getDeclaredMethods(Unknown Source) ~[?:?] {}
        at net.neoforged.bus.EventBus.register(EventBus.java:105) ~[bus-8.0.5.jar:?] {}
        at TRANSFORMER/chunkyborder@1.2.24/org.popcraft.chunkyborder.ChunkyBorderNeoForge.<init>(ChunkyBorderNeoForge.java:64) ~[ChunkyBorder-NeoForge-1.2.24.jar:?] {}
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
        at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:118) ~[loader-10.0.36.jar:10.0] {}
        at net.neoforged.fml.ModLoader.lambda$constructMods$0(ModLoader.java:125) ~[loader-10.0.36.jar:10.0] {}
        at net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$4(ModLoader.java:203) ~[loader-10.0.36.jar:10.0] {}
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}


-- System Details --
Details:
        Minecraft Version: 1.21.11
        Minecraft Version ID: 1.21.11
        Operating System: Linux (amd64) version 6.12.86+deb13-amd64
        Java Version: 21.0.11, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 3980968768 bytes (3796 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 4
        Processor Vendor: AuthenticAMD
        Processor Name: AMD EPYC-Milan Processor
        Identifier: AuthenticAMD Family 25 Model 1 Stepping 1
        Microarchitecture: Zen 3
        Frequency (GHz): -0.00
        Number of physical packages: 4
        Number of physical CPUs: 4
        Number of logical CPUs: 4
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MiB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MiB): 3878.65
        Virtual memory used (MiB): 3168.03
        Swap memory total (MiB): 0.00
        Swap memory used (MiB): 0.00
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 63389.85, total: 75386.56
        Space in storage for workdir (MiB): available: 63389.85, total: 75386.56
        JVM Flags: 2 total; -Xmx4G -Xms4G
        Debug Flags: 0 total; 
        Class Processors: 
                00.00%: neoforge:computing_frames (marker)
                00.00%: neoforge:runtime_enum_extender
                05.38%: neoforge:access_transformer
                00.12%: neoforge:mixin
                00.00%: neoforge:simple_processors_default (marker)
                00.02%: neoforge.coremods:field_to_getter.net.minecraft.world.level.biome.biome
                00.02%: neoforge.coremods:field_to_getter.net.minecraft.world.level.block.flowerpotblock
                00.02%: neoforge.coremods:field_to_getter.net.minecraft.world.level.levelgen.structure.structure
                00.42%: neoforge.coremods:method_redirector
        Mod List: 
                Chunky-NeoForge-1.4.54.jar                        |Chunky                        |chunky                        |1.4.54              |Manifest: 97984c8d99d41afbd0a0381a7de47203ee0bf26259c2e8a8bf676d5de78b46fc
                ChunkyBorder-NeoForge-1.2.24.jar                  |ChunkyBorder                  |chunkyborder                  |1.2.24              |Manifest: 86a07b3f97c0109498007f9fce43e26cc633d975a4b62c75ff3bde1944e93612
                jei-1.21.11-neoforge-27.4.0.22.jar                |Just Enough Items             |jei                           |27.4.0.22           |Manifest: cf29e64a7a50c28078415dd742c35bf2d910a628e7a19b42651155a59bc9abf4
                minecraft-server-patched-21.11.42.jar             |Minecraft                     |minecraft                     |1.21.11             |Manifest: 341a617e8af8a5a9b4c35b247fe21cd2cc84fa71ebe0959cc4f740d3b6b5a905
                neoforge-21.11.42-universal.jar                   |NeoForge                      |neoforge                      |21.11.42            |Manifest: 0bba6d7cedc69ab53a308aacc8acd270e0739a9ce7341aed5185dc3480ca2673
                TAB v6.0.1.jar                                    |TAB                           |tab                           |6.0.1               |Manifest: 2811fa2dd8c080b12696fcad139bbb9360829b18565d31e3a670945bb1ac8a8b
        Crash Report UUID: 824b4788-2f94-4d08-8cf6-bda5d4171b7b
        FML: 10.0.36
        NeoForge: 21.11.42
```

_But if you have a solution to this problem and this version should work on 1.21.11, please let me know <3_
